//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LP2Rest.ReporteWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.lp2rest.pucp.edu.pe/", ConfigurationName="ReporteWS.ReporteWS")]
    public interface ReporteWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha_ini del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2rest.pucp.edu.pe/ReporteWS/generarReporteAsistenciaRequest", ReplyAction="http://services.lp2rest.pucp.edu.pe/ReporteWS/generarReporteAsistenciaResponse")]
        LP2Rest.ReporteWS.generarReporteAsistenciaResponse generarReporteAsistencia(LP2Rest.ReporteWS.generarReporteAsistenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2rest.pucp.edu.pe/ReporteWS/generarReporteAsistenciaRequest", ReplyAction="http://services.lp2rest.pucp.edu.pe/ReporteWS/generarReporteAsistenciaResponse")]
        System.Threading.Tasks.Task<LP2Rest.ReporteWS.generarReporteAsistenciaResponse> generarReporteAsistenciaAsync(LP2Rest.ReporteWS.generarReporteAsistenciaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReporteAsistenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReporteAsistencia", Namespace="http://services.lp2rest.pucp.edu.pe/", Order=0)]
        public LP2Rest.ReporteWS.generarReporteAsistenciaRequestBody Body;
        
        public generarReporteAsistenciaRequest() {
        }
        
        public generarReporteAsistenciaRequest(LP2Rest.ReporteWS.generarReporteAsistenciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReporteAsistenciaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_cuentaUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha_ini;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fecha_fin;
        
        public generarReporteAsistenciaRequestBody() {
        }
        
        public generarReporteAsistenciaRequestBody(int id_cuentaUsuario, string fecha_ini, string fecha_fin) {
            this.id_cuentaUsuario = id_cuentaUsuario;
            this.fecha_ini = fecha_ini;
            this.fecha_fin = fecha_fin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReporteAsistenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReporteAsistenciaResponse", Namespace="http://services.lp2rest.pucp.edu.pe/", Order=0)]
        public LP2Rest.ReporteWS.generarReporteAsistenciaResponseBody Body;
        
        public generarReporteAsistenciaResponse() {
        }
        
        public generarReporteAsistenciaResponse(LP2Rest.ReporteWS.generarReporteAsistenciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReporteAsistenciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] @return;
        
        public generarReporteAsistenciaResponseBody() {
        }
        
        public generarReporteAsistenciaResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReporteWSChannel : LP2Rest.ReporteWS.ReporteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteWSClient : System.ServiceModel.ClientBase<LP2Rest.ReporteWS.ReporteWS>, LP2Rest.ReporteWS.ReporteWS {
        
        public ReporteWSClient() {
        }
        
        public ReporteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Rest.ReporteWS.generarReporteAsistenciaResponse LP2Rest.ReporteWS.ReporteWS.generarReporteAsistencia(LP2Rest.ReporteWS.generarReporteAsistenciaRequest request) {
            return base.Channel.generarReporteAsistencia(request);
        }
        
        public byte[] generarReporteAsistencia(int id_cuentaUsuario, string fecha_ini, string fecha_fin) {
            LP2Rest.ReporteWS.generarReporteAsistenciaRequest inValue = new LP2Rest.ReporteWS.generarReporteAsistenciaRequest();
            inValue.Body = new LP2Rest.ReporteWS.generarReporteAsistenciaRequestBody();
            inValue.Body.id_cuentaUsuario = id_cuentaUsuario;
            inValue.Body.fecha_ini = fecha_ini;
            inValue.Body.fecha_fin = fecha_fin;
            LP2Rest.ReporteWS.generarReporteAsistenciaResponse retVal = ((LP2Rest.ReporteWS.ReporteWS)(this)).generarReporteAsistencia(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Rest.ReporteWS.generarReporteAsistenciaResponse> LP2Rest.ReporteWS.ReporteWS.generarReporteAsistenciaAsync(LP2Rest.ReporteWS.generarReporteAsistenciaRequest request) {
            return base.Channel.generarReporteAsistenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Rest.ReporteWS.generarReporteAsistenciaResponse> generarReporteAsistenciaAsync(int id_cuentaUsuario, string fecha_ini, string fecha_fin) {
            LP2Rest.ReporteWS.generarReporteAsistenciaRequest inValue = new LP2Rest.ReporteWS.generarReporteAsistenciaRequest();
            inValue.Body = new LP2Rest.ReporteWS.generarReporteAsistenciaRequestBody();
            inValue.Body.id_cuentaUsuario = id_cuentaUsuario;
            inValue.Body.fecha_ini = fecha_ini;
            inValue.Body.fecha_fin = fecha_fin;
            return ((LP2Rest.ReporteWS.ReporteWS)(this)).generarReporteAsistenciaAsync(inValue);
        }
    }
}
